name: Extract VPN Zip File

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  unzip-process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Unzip File Directly into Repo
        run: |
          unzip VPN.zip -d .
          rm VPN.zip

      - name: Commit Extracted Files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Extracted all source files from VPN.zip"
